apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart1.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart1.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        ports:
        - containerPort: {{ .Values.container.ports }}